//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entreprise
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class activite
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<double> Frais { get; set; }
        public Nullable<double> Revenue { get; set; }
        public string descript { get; set; }

        public static List<activite> getAllActivities()
        {
            BDGestionAssociationEntities3 bd = new BDGestionAssociationEntities3();
            List<activite> ls = bd.activites.ToList<activite>();
            return ls;
        }

        public static activite searchActivity(string id)
        {
            BDGestionAssociationEntities3 bd = new BDGestionAssociationEntities3();
            activite ac = bd.activites.Where(us => us.ID.Equals(id)).FirstOrDefault();
            return ac;
        }

        public static bool Add_Activiti(string id, DateTime DateDebut, DateTime DateFin, double frais, double revenue, string description)
        {
            BDGestionAssociationEntities3 bd = new BDGestionAssociationEntities3();
            activite ac = new activite();
            try
            {
                ac.ID = id;
                ac.DateDebut = DateDebut;
                ac.DateFin = DateFin;
                ac.Frais = frais;
                ac.Revenue = revenue;
                ac.descript = description;
                bd.activites.Add(ac);
                bd.SaveChanges();
            }
            catch (Exception) { return false; }
            return true;
        }

        public static bool Modify_Activiti(string id0, string id, DateTime DateDebut, DateTime DateFin, double frais, double revenue, string description)
        {
            BDGestionAssociationEntities3 bd = new BDGestionAssociationEntities3();
            activite ac = bd.activites.Where(us => us.ID.Equals(id0)).FirstOrDefault();
            if (ac == null) return false;
            try
            {
                ac.ID = id;
                ac.DateDebut = DateDebut;
                ac.DateFin = DateFin;
                ac.Frais = frais;
                ac.Revenue = revenue;
                ac.descript = description;
                bd.SaveChanges();
            }
            catch (Exception) { return false; }
            return true;
        }

        public static bool Delete_Activiti(string id)
        {
            BDGestionAssociationEntities3 bd = new BDGestionAssociationEntities3();
            activite ac = bd.activites.Where(us => us.ID.Equals(id)).FirstOrDefault();
            if (ac == null) return false;
            try
            {
                bd.activites.Remove(ac);
                bd.SaveChanges();
            }
            catch (Exception) { return false; }
            return true;
        }

        public static string ActivitieDescription(string id)
        {
            BDGestionAssociationEntities3 bd = new BDGestionAssociationEntities3();
            string description = bd.activites.Where(ac => ac.ID.Equals(id)).FirstOrDefault().descript;
            return description;
        }
    }
}
