//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entreprise
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDGestionAssociationEntities3 : DbContext
    {
        public BDGestionAssociationEntities3()
            : base("name=BDGestionAssociationEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activite> activites { get; set; }
        public DbSet<adherent> adherents { get; set; }
        public DbSet<financement> financements { get; set; }
        public DbSet<Month> Months { get; set; }
        public DbSet<utilisateur> utilisateurs { get; set; }
    }
}
