//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entreprise
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Month
    {
        public int id { get; set; }
        public string nom { get; set; }

        public static List<Month> getMonths()
        {
            BDGestionAssociationEntities3 bd = new BDGestionAssociationEntities3();
            List<Month> ls = bd.Months.ToList<Month>();
            return ls;
        }
    }
}
